default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: react_try_development

test:
  <<: *default
  database: react_try_test

production:
  <<: *default
  database: react_try_production
  username: react_try
  password: <%= ENV['DEVISE_DATABASE_PASSWORD'] %>